database:
  url: jdbc:h2:./target/app
  driverClass: org.h2.Driver
  user: sa
  password: sa

  properties:
    hibernate.hbm2ddl.auto: update #create #
    hibernate.dialect: org.hibernate.dialect.H2Dialect

#httpClient:
#  connectionTimeout: 5000ms
#  timeout: 5000ms
